apiVersion: v1
kind: Service
metadata:
  name: synapseos-api
  namespace: synapseos
spec:
  type: ClusterIP
  selector:
    app: synapseos-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
